# Example markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  code_blocks: false
  # Fenced code languages to ignore
  ignore_code_languages: []
  # Number of spaces for each hard tab
  spaces_per_tab: 4

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 120
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: false
  # Strict length checking
  strict: false
  # Stern length checking
  stern: true

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  # nobr needed to avoid breaking target names in toctree
  allowed_elements: [img, details, summary, nobr]

# MD024/no-duplicate-heading Multiple headings with the same content
MD024:
  # Ignore duplicates on different levels
  siblings_only: true
