#!/usr/bin/env python3
#
# Simple utility to automatically generate the port list doc page
# from the JSON output of `port_manager validate`.
#
# Copyright 2026 Phoenix Systems
# Author: Adam Greloch
#
# SPDX-License-Identifier: BSD-3-Clause
#

import json
import sys
from argparse import ArgumentParser
from pathlib import Path

port_def_root = "https://github.com/phoenix-rtos/phoenix-rtos-ports/blob/master"
port_docs_path = Path("./ports")


def to_backticked_list(params: list[str]) -> str:
    if params:
        return ", ".join([f"`{s}`" for s in params])
    else:
        return "*(none)*"


def generate_markdown(data: dict) -> str:
    lines = []

    lines.append(
        f"""<!-- DO NOT EDIT: this file is automatically generated using {Path(__file__).name} -->
<!-- markdownlint-disable MD013 -->
"""
    )

    lines.append(f"""# List of available ports

The following list has been automatically generated from port definitions available
on the `master` branch of
[phoenix-rtos-ports]({port_def_root})
repository.

Legend:

* `phoenix` and `host` -- OS requirements
* `[o]` -- optional dependency
* `[!]` -- conflict
""")

    for port_name, versions in sorted(data.items()):
        for version_key, details in versions.items():
            version = details.get("version", version_key)

            lines.append(f"## {port_name}-{version}\n")

            desc = details.get("desc", "").strip()
            port_def_path = details.get("port_def_path", "")
            requirements = details.get("requirements", [])
            conflicts = details.get("conflicts", [])
            iuse = details.get("iuse", [])

            if desc:
                lines.append(f"{desc}")

            lines.append("")

            doc_md_filename = f"{port_name}.md"
            port_doc = port_docs_path.joinpath(doc_md_filename)
            if port_doc.exists():
                lines.append("* **Related doc page:** {doc}" + f"`{port_name}`")

            lines.append(
                f"* **Defined in:** [`{port_def_path}`]({port_def_root}/{port_def_path})"
            )
            lines.append(f"* **Available flags:** {to_backticked_list(iuse)}")
            lines.append(f"* **Requires:** {to_backticked_list(requirements)}")
            lines.append(f"* **Conflicts:** {to_backticked_list(conflicts)}")
            lines.append("")

    return "\n".join(lines)


def main():
    parser = ArgumentParser()
    parser.add_argument(
        "input_json",
        help="path to input json (should be generated using `port_manager validate`)",
    )
    parser.add_argument("output_md", help="markdown output destination path")

    if len(sys.argv) == 1:
        parser.print_help()
    args = parser.parse_args(sys.argv[1:])

    with Path(args.input_json).open("r", encoding="utf-8") as f:
        data = json.load(f)

    markdown = generate_markdown(data)

    with Path(args.output_md).open("w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"Markdown file generated: {args.output_md}")


if __name__ == "__main__":
    main()
