# vim:sw=2:ts=2
# build html version of docs
name: build

# on events
on:
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v4
      - uses: sphinx-doc/github-problem-matcher@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build docs
        run: |
          make clean html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html_build
          path: _build
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    name: deploy-on-merge
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: html_build
          path: _build
          if-no-files-found: error

      - name: Install lftp
        run: |
          sudo apt install -y lftp

      - name: Deploy docs
        run: |
          ls -la
          lftp -v -c "open -u lftp:1234 81.15.242.168:11022; ls"
